name: plex

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - PLEX_CLAIM=${PLEX_KEY}
    network_mode: host
    volumes:
      - ./config:/config
      - ./transcode:/transcode
      - ./data:/data
